import json

cell_1_markdown = "# Alien Planet Globe Generator\n\nThis notebook generates a 3D globe projection from a 2D map image using OpenCV and Matplotlib."

cell_2_lines = [
    "%matplotlib inline",
    "import cv2 # OpenCV for image loading and basic manipulation (better than Pillow for this)",
    "import numpy as np",
    "import matplotlib.pyplot as plt",
    "from mpl_toolkits.mplot3d import Axes3D",
    "from matplotlib import cm",
    "from IPython.display import display",
    "import plotly.graph_objects as go",
    "",
    "# --- Configuration ---",
    "MAP_IMAGE_PATH = 'Motoki_Aspsp_uk_Fig02_c_Islands.jpg' # Replace with the path to your image",
    "OUTPUT_IMAGE_PATH = 'globe_projection.png'",
    "GLOBE_RADIUS = 1.0 # Arbitrary radius for the 3D projection",
    "OCEAN_COLOR = (50, 150, 255) # RGB for ocean (blue shades)",
    "CONTINENT_COLOR = (150, 200, 50) # RGB for continents (yellow-green shades)",
    "BACKGROUND_COLOR = (0, 0, 0) # Black background for space",
    "MIN_CONTOUR_AREA = 100.0 # Minimum area to be considered land (filters out text/noise)"
]

cell_3_lines = [
    "# --- Step 1: Load and Process the Mercator Map ---",
    "def load_and_process_map(image_path):",
    "    # Loads the map image, converts it to grayscale, and identifies land/ocean.",
    "    # Assumes black outlines are land, white background is ocean initially.",
    "    ",
    "    img = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)",
    "    if img is None:",
    "        raise FileNotFoundError(f'Map image not found at {image_path}')",
    "",
    "    # Invert colors if necessary: make land white, ocean black for easier processing",
    "    # You might need to adjust this based on your exact input image (black lines, white background)",
    "    # A simple threshold can separate outlines from the white background",
    "    _, binary_map = cv2.threshold(img, 200, 255, cv2.THRESH_BINARY_INV) # outlines become white",
    "",
    "    # --- Heuristic: Remove Legend ---",
    "    # Divide the map into a 3x3 grid and force the bottom-right section to be ocean (black in binary_map)",
    "    h, w = binary_map.shape",
    "    h_step = h // 3",
    "    w_step = w // 3",
    "    # Bottom-right rectangle: rows from 2*h_step to h, cols from 2*w_step to w",
    "    binary_map[2*h_step:, 2*w_step:] = 0 ",
    "",
    "    # Now, fill the \"land\" areas. This is the trickiest part.",
    "    # We'll use flood fill starting from various points if it's not a single connected component.",
    "    # For a robust solution, you'd usually find contours and then fill them.",
    "",
    "    # Let's assume the input is black outlines on white. We need to fill *inside* the outlines.",
    "    # This is a common image processing problem. One way is to find contours, then draw filled contours.",
    "    contours, _ = cv2.findContours(binary_map, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)",
    "    ",
    "    # Filter contours based on area to remove text/noise",
    "    # We use MIN_CONTOUR_AREA from configuration",
    "    contours = [cnt for cnt in contours if cv2.contourArea(cnt) > MIN_CONTOUR_AREA]",
    "",
    "    height, width = img.shape",
    "    colored_map = np.zeros((height, width, 3), dtype=np.uint8) # RGB image for colored map",
    "",
    "    # Start with ocean",
    "    colored_map[:] = OCEAN_COLOR",
    "",
    "    # Draw filled contours for continents",
    "    # This assumes the black lines define closed continents.",
    "    # If the lines are just outlines without an explicit \"fill\", you'll need a more advanced filling algorithm.",
    "    cv2.drawContours(colored_map, contours, -1, CONTINENT_COLOR, cv2.FILLED)",
    "",
    "    # Convert to a boolean mask for easier projection",
    "    # True for land, False for ocean",
    "    land_mask = (cv2.cvtColor(colored_map, cv2.COLOR_RGB2GRAY) == cv2.cvtColor(np.array([[CONTINENT_COLOR]], dtype=np.uint8), cv2.COLOR_RGB2GRAY)[0,0])",
    "",
    "    cv2.imwrite('debug_2d_map.png', cv2.cvtColor(colored_map, cv2.COLOR_RGB2BGR))",
    "    return land_mask, colored_map # Return mask and the 2D colored map for reference"
]

cell_4_lines = [
    "# --- Step 2: Mercator Projection to Spherical Coordinates ---",
    "def mercator_to_spherical(x_img, y_img, img_width, img_height):",
    "    # Converts 2D Mercator pixel coordinates (x_img, y_img) to",
    "    # spherical coordinates (longitude, latitude).",
    "    ",
    "    # Normalize pixel coordinates to -1 to 1 range (or 0 to 1 then map)",
    "    # x_img: 0 to width-1 maps to -180 to 180 (or 0 to 360) longitude",
    "    # y_img: 0 to height-1 maps to typically -85 to 85 (or some Mercator limit) latitude",
    "",
    "    # Longitude: maps linearly from x_img",
    "    longitude = (x_img / img_width) * 360 - 180 # -180 to +180 degrees",
    "    longitude_rad = np.deg2rad(longitude)",
    "",
    "    # Latitude: inverse Mercator projection formula",
    "    # Mercator formula: y = R * ln(tan(pi/4 + lat/2))",
    "    # So, lat = 2 * (atan(exp(y/R)) - pi/4)",
    "    # y_normalized from -1 to 1 (or 0 to 1 and scale)",
    "    y_normalized = 2 * (y_img / img_height) - 1 # -1 at bottom (south), 1 at top (north)",
    "    latitude_rad = 2 * (np.arctan(np.exp(np.pi * y_normalized)) - np.pi / 4)",
    "    latitude = np.rad2deg(latitude_rad) # For debug/understanding",
    "",
    "    return longitude_rad, latitude_rad",
    "",
    "# --- Step 3: Spherical Coordinates to 3D Cartesian Coordinates ---",
    "def spherical_to_cartesian(lon_rad, lat_rad, radius):",
    "    # Converts spherical coordinates (longitude, latitude) to 3D Cartesian (x, y, z).",
    "    x = radius * np.cos(lat_rad) * np.cos(lon_rad)",
    "    y = radius * np.cos(lat_rad) * np.sin(lon_rad)",
    "    z = radius * np.sin(lat_rad)",
    "    return x, y, z"
]

cell_5_lines = [
    "# --- Main Program ---",
    "def create_globe_from_map(map_path, output_path):",
    "    # Load raw image for display",
    "    raw_img = cv2.imread(map_path)",
    "    if raw_img is None:",
    "        raise FileNotFoundError(f'Map image not found at {map_path}')",
    "    raw_img_rgb = cv2.cvtColor(raw_img, cv2.COLOR_BGR2RGB)",
    "",
    "    land_mask, colored_map_2d = load_and_process_map(map_path)",
    "    height, width = land_mask.shape",
    "",
    "    # --- Matplotlib: Display 2D Maps ---",
    "    fig_2d = plt.figure(figsize=(16, 8))",
    "",
    "    # Raw Input Map",
    "    ax0 = fig_2d.add_subplot(121)",
    "    ax0.imshow(raw_img_rgb)",
    "    ax0.set_title('Raw Input Map')",
    "    ax0.axis('off')",
    "",
    "    # Processed 2D Map",
    "    ax1 = fig_2d.add_subplot(122)",
    "    ax1.imshow(cv2.cvtColor(colored_map_2d, cv2.COLOR_BGR2RGB))",
    "    ax1.set_title('Processed 2D Map (Land/Ocean)')",
    "    ax1.axis('off')",
    "    ",
    "    plt.tight_layout()",
    "    plt.show()",
    "",
    "    # --- Plotly: Interactive 3D Globe ---",
    "    print('Generating interactive 3D globe with Plotly...')",
    "",
    "    # Create a mesh for the globe",
    "    # Downsample for performance if needed, but 200x200 is fine for Plotly",
    "    u = np.linspace(0, 2 * np.pi, width)",
    "    v = np.linspace(-np.pi / 2, np.pi / 2, height)",
    "    ",
    "    # Meshgrid for Plotly Surface",
    "    # Note: Plotly uses x, y, z grids",
    "    # We need to broadcast u and v to 2D grids",
    "    u_grid, v_grid = np.meshgrid(u, v)",
    "    ",
    "    x_globe = GLOBE_RADIUS * np.cos(u_grid) * np.cos(v_grid)",
    "    y_globe = GLOBE_RADIUS * np.sin(u_grid) * np.cos(v_grid)",
    "    z_globe = GLOBE_RADIUS * np.sin(v_grid)",
    "",
    "    # Surface Color",
    "    # Map Land (True) to 1, Ocean (False) to 0",
    "    surface_color = np.zeros((height, width))",
    "    surface_color[land_mask] = 1.0 ",
    "    ",
    "    # Custom colorscale: 0 -> Ocean Color, 1 -> Land Color",
    "    # Plotly colors are strings like 'rgb(r, g, b)'",
    "    def rgb_str(c): return f'rgb({c[0]},{c[1]},{c[2]})'",
    "    ",
    "    colorscale = [
    "        [0.0, rgb_str(OCEAN_COLOR)],",
    "        [0.5, rgb_str(OCEAN_COLOR)], # Threshold at 0.5",
    "        [0.5, rgb_str(CONTINENT_COLOR)],",
    "        [1.0, rgb_str(CONTINENT_COLOR)]",
    "    ]",
    "",
    "    fig_3d = go.Figure(data=[go.Surface(",
    "        x=x_globe, y=y_globe, z=z_globe,",
    "        surfacecolor=surface_color,",
    "        colorscale=colorscale,",
    "        showscale=False, # Hide the color bar",
    "        lightposition=dict(x=100, y=100, z=100), # Basic lighting",
    "        lighting=dict(ambient=0.8, diffuse=0.8) # Bright lighting",
    "    )])",
    "",
    "    fig_3d.update_layout(",
    "        title='Interactive Alien Planet Globe',",
    "        width=800,",
    "        height=800,",
    "        scene=dict(",
    "            xaxis=dict(visible=False),",
    "            yaxis=dict(visible=False),",
    "            zaxis=dict(visible=False),",
    "            bgcolor='black'",
    "        ),",
    "        paper_bgcolor='black',",
    "        font=dict(color='white')",
    "    )",
    "    ",
    "    fig_3d.show()"
]

cell_6_lines = [
    "# --- Execute ---",
    "create_globe_from_map(MAP_IMAGE_PATH, OUTPUT_IMAGE_PATH)",
    "print(\"\\nNote: For a truly smooth and photorealistic result, you'd typically use dedicated 3D rendering software (like Blender, Three.js, etc.) and apply the processed 2D map as a texture onto a sphere model.\")"
]

def make_cell(lines, cell_type="code"):
    source_with_newlines = [line + "\n" for line in lines]
    return {
        "cell_type": cell_type,
        "metadata": {},
        "outputs": [],
        "source": source_with_newlines
    }

notebook_content = {
 "cells": [
  make_cell([cell_1_markdown], "markdown"),
  make_cell(cell_2_lines),
  make_cell(cell_3_lines),
  make_cell(cell_4_lines),
  make_cell(cell_5_lines),
  make_cell(cell_6_lines)
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 4
}

with open('weorold.ipynb', 'w') as f:
    json.dump(notebook_content, f, indent=1)